<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    
    <OutputType>Exe</OutputType>
    <StartupObject>msconvert.Program</StartupObject>
    <RootNamespace>msconvert</RootNamespace>
    <AssemblyName>msconvert</AssemblyName>
    <FileAlignment>512</FileAlignment>
    
        <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <FileAlignment>512</FileAlignment>
    <UseWindowsForms>true</UseWindowsForms>
    <Configurations>Debug;Release;Rsharp_app_release;mzkit_win32;MEMI-Desktop</Configurations>
    <Platforms>AnyCPU;ARM32;x64</Platforms>
    <UseWPF>True</UseWPF>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows|AnyCPU'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows|ARM32'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-windows|x64'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows|AnyCPU'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows|ARM32'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-windows|x64'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Rsharp_app_release|net10.0-windows|AnyCPU'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Rsharp_app_release|net10.0-windows|ARM32'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Rsharp_app_release|net10.0-windows|x64'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='mzkit_win32|net10.0-windows|AnyCPU'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='mzkit_win32|net10.0-windows|ARM32'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='mzkit_win32|net10.0-windows|x64'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MEMI-Desktop|net10.0-windows|AnyCPU'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MEMI-Desktop|net10.0-windows|ARM32'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MEMI-Desktop|net10.0-windows|x64'">
    <OutputPath>G:\mzkit\dist\bin</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="logs\**" />
    <EmbeddedResource Remove="logs\**" />
    <None Remove="logs\**" />
    <Page Remove="logs\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\GCModeller\src\runtime\sciBASIC#\Data\BinaryData\HDSPack\HDSPack.vbproj" />
    <ProjectReference Include="..\..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\assembly\assembly\assembly-netcore5.vbproj" />
    <ProjectReference Include="..\..\assembly\BrukerDataReader\BrukerDataReader.NET5.vbproj" />
    <ProjectReference Include="..\..\assembly\mzPackExtensions\mzPackExtensions.NET5.vbproj" />
    <ProjectReference Include="..\..\assembly\mzPack\mzpack.NET5.vbproj" />
    <ProjectReference Include="..\..\assembly\sciexWiffReader\sciexWiffReader.vbproj" />
    <ProjectReference Include="..\..\assembly\ThermoRawFileReader\MSFileReader.NET5.vbproj" />
    <ProjectReference Include="..\..\mzmath\ms2_math-core\mzmath-netcore5.vbproj" />
    <ProjectReference Include="..\services\Task\Task.vbproj" />
  </ItemGroup>
  
</Project>