<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <StartupObject>msconvertGUI.My.MyApplication</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <OutputPath>../../../dist\bin</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;mzkit_win32</Configurations>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Product>BioDeep</Product>
    <Company>PANOMIX</Company>
    <Authors>xieguigang@metabolomics.ac.cn</Authors>
    <Title>Convert Mass Spectrum Raw Data Files</Title>
    <Description>Convert Mass Spectrum Raw Data Files Into MZKit Format</Description>
    <RootNamespace>BioNovoGene.mzkit_win32</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="My Project\Settings.Designer.vb">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>
 </Project>