<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>pkgTool</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <OutputPath>../../../../dist\bin\plugins</OutputPath>
    <Platforms>AnyCPU;x64</Platforms>
    <Configurations>Debug;Release;mzkit_win32</Configurations>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(ProjectDir)**\*.cs</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\galaxy\src\GalaxyData\GalaxyData.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\galaxy\src\GalaxyForm\GalaxyForm.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\galaxy\src\GalaxyWorkbench\GalaxyWorkbench.vbproj" />
    <ProjectReference Include="..\..\..\..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\BasicMDIForm\BasicMDIForm.vbproj" />
  </ItemGroup>
 </Project>