<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <Configurations>Debug;Release;Rsharp_app_release;mzkit_win32</Configurations>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Platforms>AnyCPU;ARM32;x64</Platforms>
    <AssemblyName>Mzkit_win32.Task</AssemblyName>
    <RootNamespace>Task</RootNamespace>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\GCModeller\src\runtime\sciBASIC#\Microsoft.VisualBasic.Core\src\Core.vbproj" />
    <ProjectReference Include="..\..\..\..\..\GCModeller\src\runtime\sciBASIC#\mime\application%json\JSON-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\assembly\assembly\assembly-netcore5.vbproj" />
    <ProjectReference Include="..\..\..\assembly\Comprehensive\Comprehensive.NET5.vbproj" />
    <ProjectReference Include="..\..\..\assembly\mzPack\mzpack.NET5.vbproj" />
    <ProjectReference Include="..\..\..\metadna\metaDNA\metaDNA.NET5.vbproj" />
    <ProjectReference Include="..\..\..\mzmath\TargetedMetabolomics\Targetted.NET5.vbproj" />
    <ProjectReference Include="..\..\..\visualize\plot\MsPlot.NET5.vbproj" />
    <ProjectReference Include="..\..\ux\Canvas\src\MzBlender\BlenderCommonLibs\BlenderCommonLibs.vbproj" />
    <ProjectReference Include="..\BioDeep\BioDeep.vbproj" />
    <ProjectReference Include="..\MZWorkRedis\MZWorkRedis.vbproj" />
    <ProjectReference Include="..\TaskStream\TaskStream.vbproj" />
  </ItemGroup>
</Project>